# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      angular:
        patterns:
        - "@angular*"
        update-types:
        - "minor"
        - "patch"
        ignore:
        - dependency-name: "@angular*"
          update-types: ["version-update:semver-major"]
      nestjs:
        patterns:
        - "@nestjs*"
        update-types:
        - "minor"
        - "patch"
      nrwl:
        patterns:
        - "@nrwl*"
        update-types:
        - "minor"
        - "patch"
    
